### ISSUE TITLE
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: 

### ISSUE THREAD

**Issue by ryantheleach** [modwizcode/VanillaBuild#1]
[main] INFO VanillaBuildMain - Checking for updates to existing SpongeVanilla repository.
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: C:\Users\Ryan\Desktop\SpongeServer\SpongeVanilla
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:579)
	at org.eclipse.jgit.api.Git.open(Git.java:116)
	at org.eclipse.jgit.api.Git.open(Git.java:99)
	at VanillaBuildMain.updateRepo(VanillaBuildMain.java:95)
	at VanillaBuildMain.main(VanillaBuildMain.java:54)
[main] ERROR VanillaBuildMain - An error occurred while updating the repository. Exiting.

After attempting to run VanillaBuild. Is there a dependency / pre-requisite? if so It would be nice if this could be documented somewhere.

**Comment by ryantheleach** [comment]
Worked it out. Had a empty folder named SpongeVanilla in the same folder as VanillaBuild that I was going to launch the build from once VB built it. Didn't realize it was clashing with names.

**Comment by modwizcode** [comment]
Glad you filed an issue, I'm going to try and make it report issues to pastebin so I can easily get the logs.
